"""phase 2: recipes, meal plans, grocery, nutrition, trial columns

Revision ID: 53887de23c05
Revises: 0e2925feaeb9
Create Date: 2026-07-13 14:46:47.264470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53887de23c05'
down_revision: Union[str, Sequence[str], None] = '0e2925feaeb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_profile_id', sa.Uuid(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_profile_id'], ['family_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_profile_id', 'week_start_date')
    )
    op.create_table('nutrition_days',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_profile_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('legumes', sa.Boolean(), nullable=False),
    sa.Column('leafy_greens', sa.Boolean(), nullable=False),
    sa.Column('nuts_seeds', sa.Boolean(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_profile_id'], ['family_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_profile_id', 'date')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_profile_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='mealtype'), nullable=False),
    sa.Column('cuisine', sa.String(length=50), nullable=True),
    sa.Column('protein', sa.String(length=50), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('total_minutes', sa.Integer(), nullable=True),
    sa.Column('active_minutes', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('nutrition_tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instructions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('toddler_notes', sa.Text(), nullable=True),
    sa.Column('infant_notes', sa.Text(), nullable=True),
    sa.Column('night2_notes', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('ai', 'manual', name='recipesource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_profile_id'], ['family_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grocery_lists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_profile_id', sa.Uuid(), nullable=False),
    sa.Column('meal_plan_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('strategy_note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_profile_id'], ['family_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_plan_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meal_plan_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='mealtype'), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_plan_id', 'day_of_week', 'meal_type')
    )
    op.create_table('grocery_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('grocery_list_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('store', sa.String(length=100), nullable=True),
    sa.Column('deal_note', sa.String(length=200), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grocery_list_id'], ['grocery_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('plan', sa.String(length=20), nullable=False, server_default='trial'))
    op.add_column('users', sa.Column('plan_status', sa.String(length=20), nullable=False, server_default='active'))
    op.add_column('users', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
    # Existing users get a fresh 21-day trial starting now
    op.execute("UPDATE users SET trial_ends_at = now() + interval '21 days' WHERE trial_ends_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'trial_ends_at')
    op.drop_column('users', 'plan_status')
    op.drop_column('users', 'plan')
    op.drop_table('grocery_items')
    op.drop_table('meal_plan_entries')
    op.drop_table('grocery_lists')
    op.drop_table('recipes')
    op.drop_table('nutrition_days')
    op.drop_table('meal_plans')
    # ### end Alembic commands ###
