"""custom nutrition targets replace fixed booleans

Revision ID: 6726681516a1
Revises: 53887de23c05
Create Date: 2026-07-14 21:09:31.289864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6726681516a1'
down_revision: Union[str, Sequence[str], None] = '53887de23c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_profile_id'], ['family_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_profile_id', 'name')
    )
    op.create_table('nutrition_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['nutrition_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'date')
    )
    # Data migration: seed the default targets for every existing family and
    # convert logged nutrition_days booleans into per-target checks
    op.execute("""
        INSERT INTO nutrition_targets (id, family_profile_id, name, emoji, description, examples, sort_order, is_active)
        SELECT gen_random_uuid(), fp.id, t.name, t.emoji, t.description, t.examples, t.sort_order, true
        FROM family_profiles fp
        CROSS JOIN (VALUES
            ('Legumes', '🫘', '½ cup most days', 'Black beans, chickpeas, lentils, edamame', 0),
            ('Leafy Greens', '🥬', '1 serving daily', 'Spinach, arugula, kale, romaine', 1),
            ('Nuts & Seeds', '🌰', 'Small handful most days', 'Walnuts, pepitas, pine nuts, hemp, chia, flax', 2)
        ) AS t(name, emoji, description, examples, sort_order)
    """)
    for column, target_name in (
        ("legumes", "Legumes"),
        ("leafy_greens", "Leafy Greens"),
        ("nuts_seeds", "Nuts & Seeds"),
    ):
        op.execute(f"""
            INSERT INTO nutrition_checks (id, target_id, date, note)
            SELECT gen_random_uuid(), nt.id, nd.date, nd.source_note
            FROM nutrition_days nd
            JOIN nutrition_targets nt
              ON nt.family_profile_id = nd.family_profile_id
             AND nt.name = '{target_name}'
            WHERE nd.{column} = true
        """)

    op.drop_table('nutrition_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition_days',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('family_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('legumes', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('leafy_greens', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('nuts_seeds', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('source_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['family_profile_id'], ['family_profiles.id'], name=op.f('nutrition_days_family_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('nutrition_days_pkey')),
    sa.UniqueConstraint('family_profile_id', 'date', name=op.f('nutrition_days_family_profile_id_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('nutrition_checks')
    op.drop_table('nutrition_targets')
    # ### end Alembic commands ###
