"""trusted sources and recipe attribution

Revision ID: 9f4a0391063b
Revises: 6726681516a1
Create Date: 2026-07-15 20:46:26.564270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4a0391063b'
down_revision: Union[str, Sequence[str], None] = '6726681516a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate misses enum value additions
    op.execute("ALTER TYPE recipesource ADD VALUE IF NOT EXISTS 'web'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_profile_id'], ['family_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_profile_id', 'url')
    )
    op.add_column('recipes', sa.Column('source_name', sa.String(length=100), nullable=True))
    op.add_column('recipes', sa.Column('source_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'source_url')
    op.drop_column('recipes', 'source_name')
    op.drop_table('trusted_sources')
    # ### end Alembic commands ###
